CRUD - categorias e problemas pelo admin
utfpr-gp/reclama-guarapuava-oficial-back pull request #5
Opened 2018-11-15 17:22 UTC by pedroida

- Lista de categorias e problemas

- Paginação de categorias e problemas

- Salvar/Editar/Excluir categorias e problemas

2018-11-17 12:46 UTC, Sartori-RIA reviewed
nao esta errado da forma que fez, POREM:
+ para a arquitetura restful existe a padronização dos nomes das urls
     + exemplo de nomes de url: https://laravel.com/docs/5.7/controllers#resource-controllers
+ para os repositorios o proprio Spring trata de criar aquelas query, vc só precisa escrever o nome corretamente, igual tinha mostrado ontem no escritório
+ o spring tem anotações como @PutMapping, @GetMapping, e etc para todos os métodos http
+ a classe abstrata para as entidades é uma sugestão para facilitar e todas as demais entidades terem um padrão, existe tbm um dependência dele q tem um propósito parecido, dispensando dai a classe abstrata MAS eu particularmente tive problema com essa dependência q nao conseguia encontra-la: https://www.baeldung.com/database-auditing-jpa

2018-11-17 12:46 UTC, Sartori-RIA commented on src/main/java/br/edu/utfpr/reclamaguarapuava/model/repository/OccurrenceRepository.java
> +    List<Occurrence> findByCategory(Long id);
voce nao precisa dessa quero em cima da busca se criar a busca como esta abaixo ;)
 
`List<Occurrence> findAllByProblem_CategoryId(Long id);`

2018-11-17 12:46 UTC, Sartori-RIA commented on src/main/java/br/edu/utfpr/reclamaguarapuava/model/repository/OccurrenceRepository.java
> +    List<Occurrence> findByProblem(Long id);
voce nao precisa dessa quero em cima da busca se criar a busca como esta abaixo ;)

` List<Occurrence> findAllByProblemId(Long id);`

2018-11-17 12:46 UTC, Sartori-RIA commented on src/main/java/br/edu/utfpr/reclamaguarapuava/model/repository/ProblemRepository.java
> +    List<Problem> deleteAllByCategoryId(@Param("id") Long id);
mesmo que no review anterior, no Spring você não precisa dessas @query() em cima do método se o nome do método estiver escrito certo. ele mesmo criará a quero corretamente, se estiver usando o IntelliJ IDEA Ultimate ele fornece-se um auxilio nisso ;)

2018-11-17 12:46 UTC, Sartori-RIA commented on src/main/java/br/edu/utfpr/reclamaguarapuava/model/repository/ProblemRepository.java
> +    List<Category> findAllByName(@Param("name") String name);
mesmo que nos reviews anteriores sobre @query()

2018-11-17 12:46 UTC, Sartori-RIA commented on src/main/resources/data.sql
> +INSERT IGNORE INTO state_tb (id, name) VALUES ('1', 'Paraná');
recomendo ver disso:
https://stackoverflow.com/questions/2401489/execute-method-on-startup-in-spring
para que dai logo q o servidor comece a executar ele já rode todos os scripts de população de dados e etc sem precisar se preocuparem se o nome das Fields estão corretos ;)

2018-11-17 12:46 UTC, Sartori-RIA commented on src/main/resources/application.properties
>  spring.jpa.hibernate.ddl-auto=update
o Spring possui suporte ao .yml dai esse Application pode ser renomeado para application.yml e dai ficará mais legível o arquivo ;)

2018-11-17 12:46 UTC, Sartori-RIA commented on src/main/java/br/edu/utfpr/reclamaguarapuava/model/dto/ProblemDTO.java
> +    CategoryService categoryService;
porque esta injetando o category service se o mesmo nao é utilizado dentro do DTO ?

2018-11-17 12:46 UTC, Sartori-RIA commented on src/main/java/br/edu/utfpr/reclamaguarapuava/controller/ProblemResource.java
> +    public ResponseEntity<Response<Page<ProblemDTO>>> findAllPaginationWithPage(
este metodo de paginacao nao é preciso pelo seguinte caso:
no seu findAll() basta por como um dos parâmetros do tipo Pageable e pronto ja estará com TODOS as variáveis de paginação, dai basta apenas na hr q for chamar o service.findall() já passar a paginação q o próprio Spring se responsabiliza, tem exemplo nos sources q mandei no slack do grupo

2018-11-17 12:46 UTC, Sartori-RIA commented on src/main/java/br/edu/utfpr/reclamaguarapuava/controller/ProblemResource.java
> +    public ResponseEntity<Response<Page<ProblemDTO>>> findAllPaginationWithPage(
outra coisa, seguindo a arquitetura rest a url para o findar, nao deve se chamar paginação, nem todos, nem nada, é apenas o nome do recurso:
`/api/admin/categorias`
então onde esta:
`@GetMapping(value = "/paginacao")`
deve ficar como:
`@GetMapping`

2018-11-17 12:46 UTC, Sartori-RIA commented on src/main/java/br/edu/utfpr/reclamaguarapuava/controller/ProblemResource.java
> +    public ResponseEntity<Response<ProblemDTO>> store(@Valid @RequestBody ProblemDTO dto, BindingResult result) {
mudar para   `@PostMapping` e deixar sem o `value = "/salvar"`
na arquitetura rest a açao de salvar deve ser assim como no findar, apenas o nome do recurso ou seja: `/api/admin/categorias`

2018-11-17 12:46 UTC, Sartori-RIA commented on src/main/java/br/edu/utfpr/reclamaguarapuava/controller/CategoryResource.java
> +import br.edu.utfpr.reclamaguarapuava.model.dto.CategoryDTO;
exatamente as mesmas coisas que comentei em ProblemResource,

2018-11-17 12:46 UTC, Sartori-RIA commented on src/main/java/br/edu/utfpr/reclamaguarapuava/controller/CategoryResource.java
> +    public ResponseEntity<Response<CategoryDTO>> getById(@PathVariable Long id) {
trocar para @GetMapping(value ="/{id}")

2018-11-17 12:46 UTC, Sartori-RIA commented on src/main/java/br/edu/utfpr/reclamaguarapuava/controller/ProblemResource.java
> +    public ResponseEntity<Response<ProblemDTO>> getById(@PathVariable Long id) {
trocar para @GetMapping(value ="/{id}")

2018-11-17 12:46 UTC, Sartori-RIA commented on src/main/java/br/edu/utfpr/reclamaguarapuava/controller/ProblemResource.java
> +    public List<Problem> index() {
trocar para @GetMapping

2018-11-17 12:46 UTC, Sartori-RIA commented on src/main/java/br/edu/utfpr/reclamaguarapuava/model/Category.java
>  import lombok.AllArgsConstructor;
para as entidades criar essa super classe e herda-la para que dai todas as classes filhas já possuam id, data de criação e atualização e os eventos para quando inserir e atualizar:

```java

@Getter
@MappedSuperclass
public class AbstractEntity {
    private Long id;
    
    @Temporal(TemporalType.TIMESTAMP)
    private Date createdAt;
    
    @Temporal(TemporalType.TIMESTAMP)
    private Date updatedAt;
    
    @PrePersist
    public void prePersist(){
        updatedAt = new Date();
        createdAt = new Date();
    }
    
    @PreUpdate
    public void preUpdate(){
        updatedAt = new Date();
    }
}

```

2018-11-17 12:46 UTC, Sartori-RIA commented on src/main/java/br/edu/utfpr/reclamaguarapuava/model/repository/CategoryRepository.java
> +    Optional<Category> findByName(String name);
mesma coisa que os outros repositórios, nao precisa de @query() se o nome do método estiver ok

2018-11-21 02:01 UTC, ronifabio requested changes
Resolver os apontamentos para que a PR seja aceita

2018-11-21 02:01 UTC, ronifabio commented on src/main/java/br/edu/utfpr/reclamaguarapuava/controller/ProblemResource.java
> +    public ResponseEntity<Response<Page<Problem>>> index(Pageable pageable) {
O retorno precisa ser um Page do tipo DTO.

2018-11-21 02:01 UTC, ronifabio commented on src/main/java/br/edu/utfpr/reclamaguarapuava/model/dto/CategoryDTO.java
> +public class CategoryDTO {
Usar Lombok para gerar os gets, sets e contrutores nos DTOs

2018-11-21 02:01 UTC, ronifabio commented on src/main/resources/application.properties
>  spring.jpa.hibernate.ddl-auto=update
Por enquanto, vamos continuar usando .properties por ser mais simples e evitar problemas com espaçamentos para quem não conhece esta notação.

2018-11-22 17:14 UTC, ronifabio commented
Conflitos resolvidos no master

2018-11-22 17:14 UTC, closed without merging